export const LANGUAGES = {
  en: { locale: "en-GB" },
  th: { locale: "th-TH" },
};

// Values may be { one, other } for counts; pass { n } to pick the form.
export const STRINGS = {
  en: {
    // Layout
    skipToContent: "Skip to content",
    mainNav: "Main",
    navProgress: "Progress",
    navStudy: "Study",
    switchLanguage: "เปลี่ยนเป็นภาษาไทย",
    themeButton: "Theme: {theme}. Click to change.",
    theme_auto: "match device",
    theme_light: "light",
    theme_dark: "dark",
    signOutAs: "Sign out ({user})",
    signedOut: "Signed out.",
    footerDisclaimer: "Unofficial and read-only. Not affiliated with KMITL, EF or English Discoveries.",
    footerSource: "Source code",
    footerCredits: "Credits:",
    close: "Close",
    loading: "Loading",

    // Errors
    errActiveSession: "ED22 says you are already signed in on the website. Sign out at ed22.engdis.com/thai, then try again.",
    errCredentials: "Student ID or password is incorrect.",
    errServer: "ED22 returned an error (HTTP {status}). Try again in a moment.",
    errNetwork: "Could not reach ED22. Check your connection and try again.",
    errUnknown: "Something went wrong. Try again.",
    errPasswordRequired: "Enter your ED22 password.",
    errStudentId: "Enter your 8-digit KMITL student ID.",
    tryAgain: "Try again",
    storageBlocked: "Your browser blocked saving. Changes will be lost when you close this page.",

    // Sign in
    signInTitle: "Sign in with your ED22 account",
    signInSubtitle: "See your English Discoveries progress and what's left to do.",
    sessionExpired: "Your session ended. Sign in again to continue.",
    studentId: "Student ID",
    password: "ED22 password",
    showPassword: "Show password",
    hidePassword: "Hide password",
    rememberMe: "Keep me signed in on this device",
    rememberHint: "Up to 12 hours. Leave off on shared computers.",
    signIn: "Sign in",
    signingIn: "Signing in…",
    forceLoginHint: "Signing in here signs you out of ED22 in other browser tabs.",
    privacyTitle: "Your account stays yours",
    privacyDirect: "Your password goes straight from this browser to ED22. It is never stored.",
    privacyNoServer: "This site has no server, no tracking and no ads. Everything runs in your browser.",
    privacyReadOnly: "Read-only: it cannot mark lessons done, submit answers or change anything on ED22.",
    privacyOpenSource: "Open source, so anyone can check this.",
    studyWithoutSignIn: "Use flashcards without signing in",

    // Dashboard
    hello: "Signed in as {user}",
    overallProgress: "Overall progress",
    unitsComplete: "{n} of {total} units complete",
    grade: "Grade",
    seeWhatsLeft: "See what's left",
    refresh: "Refresh",
    refreshing: "Refreshing…",
    refreshed: "Progress updated.",
    updatedAt: "Updated at {time}",
    defaultPwTitle: "You are using the default password.",
    defaultPwBody: "Anyone who knows your student ID can sign in as you. Change it on",
    units: "Units",
    statusDone: "Complete",
    statusNotStarted: "Not started",
    statusInProgress: "In progress",
    statusUnknown: "Progress unknown",

    // Unit
    allUnits: "All units",
    unitNotFound: "Unit not found",
    unitNotFoundBody: "It may have been removed from your course. Go back and pick another unit.",
    lessonsComplete: "{n} of {total} lessons complete",
    filterLessons: "Show lessons",
    filterAll: "All",
    filterTodo: "To do",
    unitAllDone: "Nothing left in this unit",
    unitAllDoneBody: "Every lesson here is complete.",
    stepDone: "{step}: complete",
    stepProgress: "{step}: not finished",

    // Pending
    pendingTitle: "What's left",
    loadingUnits: "Checking units… {n} of {total}",
    pendingSummary: { one: "{n} lesson to finish across {units} unit(s).", other: "{n} lessons to finish across {units} unit(s)." },
    allDoneTitle: "All lessons complete",
    allDoneBody: "Nice work. Nothing is pending right now.",

    // Study hub
    studyTitle: "Study",
    studySubtitle: "Save vocabulary from your lessons and review it a few minutes a day. Works offline.",
    statCards: "Cards",
    statDue: "Due now",
    statMastered: "Well known",
    reviewNow: { one: "Review {n} card", other: "Review {n} cards" },
    nothingDue: "All caught up. Next review {when}.",
    noCardsYet: "No cards yet. Add a few words from your current lesson to start.",
    addWords: "Add words",
    addWordsHint: "Look up a word and save it to a lesson",
    browseCards: "Your cards",
    browseCardsHint: { one: "{n} card", other: "{n} cards" },
    lessonListTitle: "Lesson list",
    lessonListSynced: "Synced {date}: {units} units, {lessons} lessons.",
    lessonListMissing: "Sync your lesson list to tag words by lesson and include your progress in study notes.",
    lessonListMissingShort: "Sync your lesson list to pick a lesson:",
    sync: "Sync lesson list",
    resync: "Sync again",
    syncing: "Syncing… {n} of {total}",
    syncDone: "Lesson list synced: {units} units, {lessons} lessons.",
    signInToSync: "Sign in to sync",
    exportTitle: "Export and backup",
    exportBody: "Download study notes, send your cards to Anki, or move them to another device.",
    exportNotes: "Study notes (.md)",
    exportAnki: "Anki file (.txt)",
    exportBackup: "Backup (.json)",
    importBackup: "Import backup",
    backupHint: "Backups work with the ed22 command-line tool too. Importing merges cards and keeps the latest review progress.",
    importDone: { one: "Imported {n} new card, {updated} updated.", other: "Imported {n} new cards, {updated} updated." },
    importFailed: "Import failed: {reason}",
    deckCorruptTitle: "Your saved flashcards could not be read.",
    deckCorruptBody: "Nothing has been deleted. Download the data to keep it, or start fresh.",
    deckDownloadDamaged: "Download saved data",
    deckReset: "Start fresh",
    deckResetConfirm: "Delete all saved flashcards in this browser? This cannot be undone.",

    // Review
    reviewTitle: "Review",
    backToStudy: "Study",
    cardsLeft: { one: "{n} card left", other: "{n} cards left" },
    showAnswer: "Show answer",
    keySpace: "Space",
    rateLabel: "How well did you remember?",
    rateAgain: "Again",
    rateGood: "Good",
    rateEasy: "Easy",
    reviewKeysHint: "Keyboard: Space to flip, then 1, 2 or 3.",
    sessionDone: "Session complete",
    sessionSummary: "Reviewed {n} · remembered {remembered} · again {again}",
    nextDue: "Next review {when}.",
    nothingToReview: "Nothing to review right now",
    dueNow: "now",
    dueLaterToday: "later today",

    // Add words
    addWordsIntro: "Pick the lesson, type a word, then choose a meaning.",
    addedThisVisit: { one: "{n} word added. Keep going, or review it now.", other: "{n} words added. Keep going, or review them now." },
    lessonField: "Lesson",
    noLesson: "No specific lesson",
    toDoShort: "to do",
    wordField: "Word or phrase",
    wordPlaceholder: "e.g. sustainable",
    lookUp: "Look up",
    lookingUp: "Looking up…",
    skipLookup: "Skip the dictionary and write my own meaning",
    wordDuplicate: "This word is already saved for this lesson.",
    lookupNotFound: "No dictionary entry found. Write your own meaning below.",
    lookupOffline: "The dictionary is unavailable right now. Write your own meaning below.",
    pickMeaning: "Meaning",
    ownMeaning: "Write my own (English or Thai)",
    meaningField: "Your meaning",
    exampleField: "Example sentence (optional)",
    saveCard: "Save card",
    cancel: "Cancel",
    wordAdded: "Added “{word}”.",

    // Cards
    cardCount: { one: "{n} card", other: "{n} cards" },
    searchCards: "Search cards",
    noMatches: "No cards match “{query}”.",
    otherVocabulary: "Other vocabulary",
    deleteCard: "Delete “{word}”",
    cardDeleted: "Deleted “{word}”.",
    undo: "Undo",

    // App
    offlineTitle: "Can't reach ED22",
    offlineBody: "You're still signed in, but ED22 didn't respond. Check your connection.",
    notFoundTitle: "Page not found",
    notFoundBody: "The link may be old or mistyped.",
    goHome: "Go to progress",
  },

  th: {
    skipToContent: "ข้ามไปยังเนื้อหา",
    mainNav: "เมนูหลัก",
    navProgress: "ความคืบหน้า",
    navStudy: "ทบทวนคำศัพท์",
    switchLanguage: "Switch to English",
    themeButton: "ธีม: {theme} (คลิกเพื่อเปลี่ยน)",
    theme_auto: "ตามอุปกรณ์",
    theme_light: "สว่าง",
    theme_dark: "มืด",
    signOutAs: "ออกจากระบบ ({user})",
    signedOut: "ออกจากระบบแล้ว",
    footerDisclaimer: "เครื่องมือไม่เป็นทางการ อ่านข้อมูลอย่างเดียว ไม่มีส่วนเกี่ยวข้องกับ สจล. EF หรือ English Discoveries",
    footerSource: "ซอร์สโค้ด",
    footerCredits: "ขอบคุณ:",
    close: "ปิด",
    loading: "กำลังโหลด",

    errActiveSession: "ED22 แจ้งว่าคุณยังล็อกอินอยู่บนเว็บไซต์ ให้ออกจากระบบที่ ed22.engdis.com/thai ก่อน แล้วลองใหม่",
    errCredentials: "รหัสนักศึกษาหรือรหัสผ่านไม่ถูกต้อง",
    errServer: "ED22 ตอบกลับผิดพลาด (HTTP {status}) ลองใหม่อีกครั้งในอีกสักครู่",
    errNetwork: "เชื่อมต่อ ED22 ไม่ได้ ตรวจสอบอินเทอร์เน็ตแล้วลองใหม่",
    errUnknown: "เกิดข้อผิดพลาด ลองใหม่อีกครั้ง",
    errPasswordRequired: "กรอกรหัสผ่าน ED22",
    errStudentId: "กรอกรหัสนักศึกษา 8 หลัก",
    tryAgain: "ลองใหม่",
    storageBlocked: "เบราว์เซอร์ไม่อนุญาตให้บันทึกข้อมูล การเปลี่ยนแปลงจะหายเมื่อปิดหน้านี้",

    signInTitle: "เข้าสู่ระบบด้วยบัญชี ED22",
    signInSubtitle: "ดูความคืบหน้า English Discoveries และบทเรียนที่ยังเหลือ",
    sessionExpired: "เซสชันหมดอายุแล้ว เข้าสู่ระบบอีกครั้งเพื่อใช้งานต่อ",
    studentId: "รหัสนักศึกษา",
    password: "รหัสผ่าน ED22",
    showPassword: "แสดงรหัสผ่าน",
    hidePassword: "ซ่อนรหัสผ่าน",
    rememberMe: "จดจำการเข้าสู่ระบบบนอุปกรณ์นี้",
    rememberHint: "นานสุด 12 ชั่วโมง ไม่ควรเปิดบนเครื่องสาธารณะ",
    signIn: "เข้าสู่ระบบ",
    signingIn: "กำลังเข้าสู่ระบบ…",
    forceLoginHint: "การเข้าสู่ระบบที่นี่จะทำให้ ED22 ในแท็บอื่นออกจากระบบ",
    privacyTitle: "บัญชีของคุณปลอดภัย",
    privacyDirect: "รหัสผ่านส่งจากเบราว์เซอร์นี้ไปยัง ED22 โดยตรง และไม่ถูกบันทึกไว้ที่ไหนเลย",
    privacyNoServer: "เว็บนี้ไม่มีเซิร์ฟเวอร์ ไม่มีการติดตาม ไม่มีโฆษณา ทุกอย่างทำงานในเบราว์เซอร์ของคุณ",
    privacyReadOnly: "อ่านข้อมูลอย่างเดียว ไม่สามารถทำบทเรียนแทน ส่งคำตอบ หรือแก้ไขอะไรบน ED22 ได้",
    privacyOpenSource: "โอเพนซอร์ส ใครก็ตรวจสอบได้",
    studyWithoutSignIn: "ใช้แฟลชการ์ดโดยไม่ต้องเข้าสู่ระบบ",

    hello: "เข้าสู่ระบบในชื่อ {user}",
    overallProgress: "ความคืบหน้ารวม",
    unitsComplete: "เสร็จแล้ว {n} จาก {total} ยูนิต",
    grade: "เกรด",
    seeWhatsLeft: "ดูสิ่งที่ยังเหลือ",
    refresh: "รีเฟรช",
    refreshing: "กำลังรีเฟรช…",
    refreshed: "อัปเดตความคืบหน้าแล้ว",
    updatedAt: "อัปเดตเมื่อ {time}",
    defaultPwTitle: "คุณยังใช้รหัสผ่านเริ่มต้นอยู่",
    defaultPwBody: "ใครที่รู้รหัสนักศึกษาของคุณสามารถเข้าสู่ระบบแทนคุณได้ เปลี่ยนรหัสผ่านได้ที่",
    units: "ยูนิต",
    statusDone: "เสร็จแล้ว",
    statusNotStarted: "ยังไม่เริ่ม",
    statusInProgress: "กำลังเรียน",
    statusUnknown: "ไม่ทราบความคืบหน้า",

    allUnits: "ยูนิตทั้งหมด",
    unitNotFound: "ไม่พบยูนิตนี้",
    unitNotFoundBody: "ยูนิตนี้อาจถูกนำออกจากรายวิชาแล้ว กลับไปเลือกยูนิตอื่น",
    lessonsComplete: "เสร็จแล้ว {n} จาก {total} บทเรียน",
    filterLessons: "แสดงบทเรียน",
    filterAll: "ทั้งหมด",
    filterTodo: "ยังไม่เสร็จ",
    unitAllDone: "ยูนิตนี้ไม่มีอะไรค้างแล้ว",
    unitAllDoneBody: "ทำครบทุกบทเรียนในยูนิตนี้แล้ว",
    stepDone: "{step}: เสร็จแล้ว",
    stepProgress: "{step}: ยังไม่เสร็จ",

    pendingTitle: "สิ่งที่ยังเหลือ",
    loadingUnits: "กำลังตรวจสอบยูนิต… {n} จาก {total}",
    pendingSummary: "เหลือ {n} บทเรียน ใน {units} ยูนิต",
    allDoneTitle: "ทำครบทุกบทเรียนแล้ว",
    allDoneBody: "เยี่ยมมาก ตอนนี้ไม่มีอะไรค้าง",

    studyTitle: "ทบทวนคำศัพท์",
    studySubtitle: "เก็บคำศัพท์จากบทเรียน แล้วทบทวนวันละไม่กี่นาที ใช้งานออฟไลน์ได้",
    statCards: "การ์ด",
    statDue: "ถึงเวลาทบทวน",
    statMastered: "จำได้ดีแล้ว",
    reviewNow: "ทบทวน {n} การ์ด",
    nothingDue: "ทบทวนครบแล้ว รอบถัดไป{when}",
    noCardsYet: "ยังไม่มีการ์ด เริ่มจากเพิ่มคำศัพท์จากบทเรียนที่กำลังเรียนอยู่",
    addWords: "เพิ่มคำศัพท์",
    addWordsHint: "ค้นหาความหมายแล้วบันทึกไว้กับบทเรียน",
    browseCards: "การ์ดของฉัน",
    browseCardsHint: "{n} การ์ด",
    lessonListTitle: "รายชื่อบทเรียน",
    lessonListSynced: "ซิงก์เมื่อ {date}: {units} ยูนิต {lessons} บทเรียน",
    lessonListMissing: "ซิงก์รายชื่อบทเรียนเพื่อจัดคำศัพท์ตามบทเรียน และใส่ความคืบหน้าลงในสรุปบทเรียน",
    lessonListMissingShort: "ซิงก์รายชื่อบทเรียนก่อนจึงจะเลือกบทเรียนได้:",
    sync: "ซิงก์รายชื่อบทเรียน",
    resync: "ซิงก์อีกครั้ง",
    syncing: "กำลังซิงก์… {n} จาก {total}",
    syncDone: "ซิงก์แล้ว: {units} ยูนิต {lessons} บทเรียน",
    signInToSync: "เข้าสู่ระบบเพื่อซิงก์",
    exportTitle: "ส่งออกและสำรองข้อมูล",
    exportBody: "ดาวน์โหลดสรุปบทเรียน ส่งการ์ดไปใช้ใน Anki หรือย้ายไปอุปกรณ์อื่น",
    exportNotes: "สรุปบทเรียน (.md)",
    exportAnki: "ไฟล์ Anki (.txt)",
    exportBackup: "ไฟล์สำรอง (.json)",
    importBackup: "นำเข้าไฟล์สำรอง",
    backupHint: "ไฟล์สำรองใช้กับโปรแกรม ed22 แบบคอมมานด์ไลน์ได้ด้วย การนำเข้าจะรวมการ์ดและเก็บความคืบหน้าการทบทวนล่าสุดไว้",
    importDone: "นำเข้าการ์ดใหม่ {n} ใบ อัปเดต {updated} ใบ",
    importFailed: "นำเข้าไม่สำเร็จ: {reason}",
    deckCorruptTitle: "อ่านแฟลชการ์ดที่บันทึกไว้ไม่ได้",
    deckCorruptBody: "ยังไม่มีอะไรถูกลบ ดาวน์โหลดข้อมูลเก็บไว้ หรือเริ่มใหม่",
    deckDownloadDamaged: "ดาวน์โหลดข้อมูลที่บันทึกไว้",
    deckReset: "เริ่มใหม่",
    deckResetConfirm: "ลบแฟลชการ์ดทั้งหมดในเบราว์เซอร์นี้? ย้อนกลับไม่ได้",

    reviewTitle: "ทบทวน",
    backToStudy: "ทบทวนคำศัพท์",
    cardsLeft: "เหลือ {n} การ์ด",
    showAnswer: "ดูคำตอบ",
    keySpace: "Space",
    rateLabel: "จำได้ดีแค่ไหน?",
    rateAgain: "อีกครั้ง",
    rateGood: "จำได้",
    rateEasy: "ง่ายมาก",
    reviewKeysHint: "คีย์บอร์ด: กด Space เพื่อพลิกการ์ด แล้วกด 1, 2 หรือ 3",
    sessionDone: "ทบทวนครบรอบนี้แล้ว",
    sessionSummary: "ทบทวน {n} ใบ · จำได้ {remembered} · ทบทวนอีกครั้ง {again}",
    nextDue: "รอบถัดไป{when}",
    nothingToReview: "ตอนนี้ยังไม่มีการ์ดให้ทบทวน",
    dueNow: "ตอนนี้",
    dueLaterToday: "ภายในวันนี้",

    addWordsIntro: "เลือกบทเรียน พิมพ์คำศัพท์ แล้วเลือกความหมาย",
    addedThisVisit: "เพิ่มแล้ว {n} คำ เพิ่มต่อได้เลย หรือไปทบทวนตอนนี้",
    lessonField: "บทเรียน",
    noLesson: "ไม่ระบุบทเรียน",
    toDoShort: "ยังไม่เสร็จ",
    wordField: "คำศัพท์หรือวลี",
    wordPlaceholder: "เช่น sustainable",
    lookUp: "ค้นหา",
    lookingUp: "กำลังค้นหา…",
    skipLookup: "ไม่ใช้พจนานุกรม เขียนความหมายเอง",
    wordDuplicate: "คำนี้บันทึกไว้ในบทเรียนนี้แล้ว",
    lookupNotFound: "ไม่พบคำนี้ในพจนานุกรม เขียนความหมายเองด้านล่าง",
    lookupOffline: "ตอนนี้ใช้พจนานุกรมไม่ได้ เขียนความหมายเองด้านล่าง",
    pickMeaning: "ความหมาย",
    ownMeaning: "เขียนเอง (ไทยหรืออังกฤษ)",
    meaningField: "ความหมายของคุณ",
    exampleField: "ประโยคตัวอย่าง (ไม่บังคับ)",
    saveCard: "บันทึกการ์ด",
    cancel: "ยกเลิก",
    wordAdded: "เพิ่ม “{word}” แล้ว",

    cardCount: "{n} การ์ด",
    searchCards: "ค้นหาการ์ด",
    noMatches: "ไม่พบการ์ดที่ตรงกับ “{query}”",
    otherVocabulary: "คำศัพท์อื่น ๆ",
    deleteCard: "ลบ “{word}”",
    cardDeleted: "ลบ “{word}” แล้ว",
    undo: "เลิกทำ",

    offlineTitle: "เชื่อมต่อ ED22 ไม่ได้",
    offlineBody: "คุณยังอยู่ในระบบ แต่ ED22 ไม่ตอบสนอง ตรวจสอบอินเทอร์เน็ตของคุณ",
    notFoundTitle: "ไม่พบหน้านี้",
    notFoundBody: "ลิงก์อาจเก่าหรือพิมพ์ผิด",
    goHome: "ไปหน้าความคืบหน้า",
  },
};

export function translate(lang, key, vars = {}) {
  let entry = STRINGS[lang]?.[key] ?? STRINGS.en[key];
  if (entry === undefined) return key;
  if (typeof entry === "object") entry = vars.n === 1 ? entry.one : entry.other;
  return entry.replace(/\{(\w+)\}/g, (_, name) => String(vars[name] ?? ""));
}
